name: Build macOS App

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

env:
  XCODE_VERSION: "15.2"
  SCHEME_NAME: "PromptPal"
  PRODUCT_NAME: "PromptPal"

jobs:
  build:
    runs-on: macos-14
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Select Xcode version
      run: sudo xcode-select -s /Applications/Xcode_${{ env.XCODE_VERSION }}.app/Contents/Developer
      
    - name: Show Xcode version
      run: xcodebuild -version
      
    - name: Cache derived data
      uses: actions/cache@v4
      with:
        path: ~/Library/Developer/Xcode/DerivedData
        key: ${{ runner.os }}-xcode-${{ hashFiles('**/*.xcodeproj') }}-${{ hashFiles('**/Package.swift') }}
        restore-keys: |
          ${{ runner.os }}-xcode-
          
    - name: Install dependencies
      run: |
        if [ -f "Package.swift" ]; then
          xcodebuild -resolvePackageDependencies -scheme ${{ env.SCHEME_NAME }}
        fi
        
    - name: Build for testing
      run: |
        xcodebuild \
          -scheme ${{ env.SCHEME_NAME }} \
          -destination 'platform=macOS' \
          -configuration Debug \
          build-for-testing
          
    - name: Run tests
      run: |
        xcodebuild \
          -scheme ${{ env.SCHEME_NAME }} \
          -destination 'platform=macOS' \
          -configuration Debug \
          test-without-building
          
    - name: Build Release (validation only)
      run: |
        xcodebuild \
          -scheme ${{ env.SCHEME_NAME }} \
          -destination 'platform=macOS' \
          -configuration Release \
          build 